# kubernetes/mail-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mail-secret
  namespace: perpustakaan-ns
type: Opaque
stringData:
  # Ganti dengan App Password Gmail Anda yang valid
  gmail-password: "kkzrdwwplpydfxno"
