# kubernetes/mongodb-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: perpustakaan-ns
type: Opaque
stringData:
  mongo-root-username: admin
  mongo-root-password: password
