# kubernetes/monitoring/monitoring-mongodb-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  # Beri nama yang jelas, misal dengan prefix 'monitoring-'
  name: monitoring-mongodb-secret
  # PENTING: Secret ini dibuat di namespace 'monitoring-ns'
  namespace: monitoring-ns
type: Opaque
stringData:
  # Key-nya harus sama persis dengan yang dibutuhkan oleh exporter
  mongo-root-username: admin
  mongo-root-password: password
